config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :accounts, only: %i(new create)
  resource  :sessions, only: %i(new create destroy)

  get "/health", to: "health#index"

  root "pages#index"
end

app/models/account.rb
# frozen_string_literal: true

class Account < ApplicationRecord
  EMAIL_MATCHER           = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/
  MAXIMUM_EMAIL_LENGTH    = 255
  MINIMUM_PASSWORD_LENGTH = 8

  has_secure_password

  normalizes :email, with: ->(email) { email.strip.downcase }

  validates :email, presence:   true,
                    length:     { maximum: MAXIMUM_EMAIL_LENGTH },
                    format:     { with: EMAIL_MATCHER },
                    uniqueness: { case_sensitive: false }

  validates :password, length: { minimum: MINIMUM_PASSWORD_LENGTH, allow_blank: true }
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
# frozen_string_literal: true

class Current < ActiveSupport::CurrentAttributes
  attribute :account
end

app/controllers/accounts_controller.rb
# frozen_string_literal: true

class AccountsController < ApplicationController
  before_action :redirect_authenticated_account, if: :signed_in?

  rate_limit to: 5, within: 1.hour, only: :create

  # Render the new account form.
  def new
    @form = AccountForm.new
  end

  # Create a new account.
  def create
    @form = AccountForm.new(account_parameters)

    if @form.save
      start_new_session_for(@form.account)

      redirect_authenticated_account
    else
      render :new
    end
  end

  protected

  # Return the expected parameters from the required account form parameter.
  #
  # @return [ActionController::Parameters]
  def account_parameters
    params.expect(account_form: %i(email password))
  end

  # Redirect to the root.
  #
  # @return [void]
  def redirect_authenticated_account
    redirect_to root_url
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Authentication

  # Only allow modern browsers supporting webp images, web push, badges, import
  # maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/concerns/authentication.rb
# frozen_string_literal: true

module Authentication
  extend ActiveSupport::Concern

  included do
    helper_method :signed_in?,
                  :signed_out?
  end

  # Deny access by redirecting to the root URL.
  #
  # @return [void]
  def access_denied
    redirect_to new_sessions_url
  end

  # Attempt to find an account from the account ID in the session.
  #
  # @return [Account, nil]
  def account_from_session
    if session[:account_id].present?
      Account.find_by(id: session[:account_id])
    end
  end

  # Resume the account session, otherwise deny access.
  #
  # @return [void]
  def authenticate
    resume_session || access_denied
  end

  # Attempt to set the current account from the session.
  #
  # @return [Account]
  def resume_session
    Current.account ||= account_from_session
  end

  # Determine if an account is signed in.
  #
  # @return [Boolean]
  def signed_in?
    resume_session.present?
  end

  # Determine if an account is not signed in.
  #
  # @return [Boolean]
  def signed_out?
    !signed_in?
  end

  # @return [void]
  def start_new_session_for(account)
    Current.account = account

    session[:account_id] = account.id
  end

  # @return [void]
  def terminate_session
    Current.account = nil

    session.delete(:account_id)
  end
end

app/controllers/health_controller.rb
# frozen_string_literal: true

class HealthController < ActionController::Base
  CHECKS = {
    database:   -> { ActiveRecord::Base.connection.execute("SELECT 1") },
    migrations: -> { ActiveRecord::Migration.check_all_pending! }
  }.freeze

  # Render the health status based on defined checks.
  def index
    render json: results, status: status
  end

  private

  # Return a true or false result for each check being successful or not.
  #
  # @return [Hash] Each check with a true or false value.
  def results
    @results ||= CHECKS.transform_values do |method|
      method.call

      true
    rescue StandardError
      false
    end
  end

  # Return the HTTP status based on results all being successful or not.
  #
  # @return [Symbol] Either :ok or :service_unavailable based on the results.
  def status
    if results.values.all?
      :ok
    else
      :service_unavailable
    end
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  before_action :redirect_authenticated_account,
                except: :destroy,
                if:     :signed_in?

  rate_limit to: 1, within: 1.second,   only: :create, name: "ip-address"
  rate_limit to: 5, within: 30.seconds, only: :create, name: "email",
             by: -> { session_parameters[:email] }

  # Display the session form.
  def new
    @form = SessionForm.new
  end

  # Attempt to create a session from the provided parameters.
  #
  # If successful redirect, otherwise render the session form.
  def create
    @form = SessionForm.new(session_parameters)

    if @form.valid?
      start_new_session_for(@form.account)

      redirect_authenticated_account
    else
      render :new
    end
  end

  # Sign out the current account and redirect to the root.
  def destroy
    terminate_session

    redirect_to root_url
  end

  protected

  # Redirect to the root.
  #
  # @return [void]
  def redirect_authenticated_account
    redirect_to root_url
  end

  # Return the expected parameters from the required session parameter.
  #
  # @return [ActionController::Parameters]
  def session_parameters
    params.expect(session_form: %i(email password))
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/accounts/new.html.erb
<%# locals: () %>
<main class="flex flex-col justify-center py-12 px-6 min-h-full lg:px-8">
  <div class="self-center py-12 px-8 mx-auto w-full max-w-lg">
    <div class="mb-12 text-center">
      <h1 class="text-3xl font-bold text-gray-700"><%= t(".header") %></h1>
    </div>

    <%= form_for @form, url: accounts_path, data: { turbo: false }, html: { class: "highlight-errors" } do |form| %>
      <div>
        <%= form.label :email, class: "block mb-1 text-sm font-medium text-gray-800" %>
        <%= form.email_field :email, autocomplete: "email", autofocus: true, class: "w-full text-gray-800 border-gray-400 rounded focus:ring-2 focus:ring-green-200 focus:border-green-300", maxlength: Account::MAXIMUM_EMAIL_LENGTH, placeholder: t(".placeholder"), required: true %>
        <% if @form.errors[:email].present? %>
          <p class="mt-2 text-xs text-red-700"><%= Account.human_attribute_name(:email).humanize %> <%= @form.errors[:email].first %>.</p>
        <% end %>
      </div>

      <div class="mt-6">
        <%= form.label :password, class: "block mb-1 text-sm font-medium text-gray-800" %>
        <%= form.password_field :password, class: "w-full text-gray-800 border-gray-400 rounded focus:ring-2 focus:ring-green-200 focus:border-green-300", minlength: Account::MINIMUM_PASSWORD_LENGTH, required: true %>
        <% if @form.errors[:password].present? %>
          <p class="mt-2 text-xs text-red-700"><%= Account.human_attribute_name(:password).humanize %> <%= @form.errors[:password].first %>.</p>
        <% end %>
      </div>

      <button class="block p-4 mx-auto mt-6 w-4/5 text-lg font-semibold text-center text-white bg-green-600 rounded-lg hover:bg-green-500 focus:outline-none focus:drop-shadow-green-200" type="submit">
        <%= t(".submit") %>
      </button>
    <% end %>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html lang="en-US" class="antialiased text-gray-900">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <title><%= t("title") %></title>

    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>
  </head>

  <body><%= yield %></body>
</html>

app/views/pages/index.html.erb
<main class="container my-8 mx-auto w-3/4 text-center">
  <header>
    <h1 class="text-4xl text-black"><%= t("title") %></h1>
  </header>

  <p><%= t(".description") %></p>

  <% if signed_in? %>
    <%= form_tag sessions_path, class: "mt-8", method: :delete do %>
      <button type="submit" class="block mx-auto text-sm text-gray-600 cursor-pointer hover:underline">
        <%= t(".sign_out") %>
      </button>
    <% end %>
  <% else %>
    <p>
      <%= link_to t(".new_account"), new_account_path, class: "block w-1/4 py-4 mx-auto mt-6 text-sm font-semibold text-white bg-green-600 rounded-lg hover:bg-green-500 md:mt-12 md:text-xl", data: { controller: "homepage" } %>
    </p>

    <p class="mt-4 text-sm text-gray-600"><%= t(".existing_account") %> <%= link_to t(".sign_in"), new_sessions_path, class: "underline" %>.</p>
  <% end %>
</main>